import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { bold, extralight, light, regular, semibold } from "@/public/fonts";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/ClashDisplayRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/ClashDisplaySemibold.otf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../public/fonts/ClashDisplayBold.otf",
      weight: "900",
      style: "bold",
    },
    {
      path: "../public/fonts/ClashDisplayLight.otf",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/fonts/ClashDisplayExtralight.otf",
      weight: "200",
      style: "extralight",
    },
  ],
});

// const myFont = localFont({
//   src: "../public/fonts/ClashDisplayBold.otf",
//   display: "swap",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
